image: node:7.4.0

stages:
  - build
  - test
  - deploy

build client:
  stage: build
  variables:
    ENV: "production"
  script:
    - npm install
    - npm run bundle

  artifacts:
    paths:
      - dist/
      - node_modules/

test:
  stage: test
  only:
    - master

  script:
    - npm test

  coverage: /All files\s*\|\s*([\d\.]+)/

  artifacts:
    paths:
      - dist/

pages:
  image: alpine:latest
  before_script:
    - apk update && apk add bash curl ruby ruby-irb ruby-rdoc
    - gem install coderay kramdown
  stage: deploy
  script:
  # copy the app
  - mkdir -p public/demo
  - cp dist/* public/demo
  # make the website
  - mkdir -p public
  - curl http://cdn.tjaart.org/gitlab/index.html.erb --output index.html.erb
  - sed -i "s@#CI_PROJECT_URL#@${CI_PROJECT_URL}@" index.html.erb
  - 'kramdown --template index.html.erb  --syntax-highlighter coderay --syntax-highlighter-opts "{line_numbers: false}" README.md > public/index.html'
  artifacts:
    paths:
    - public
  only:
  - master

webtask:
  stage: deploy
  only:
    - master

  script:
    - 'echo \{\"default\": \{\"url\": \"https://webtask.it.auth0.com\", \"token\": \"${TOKEN}\", \"container\": \"${CONTAINER}\"\}\} > ~/.webtask'
    - npm install -g wt-cli
    - wt-cli create -s GMAIL_USERNAME=${GMAIL_USERNAME} -s GMAIL_PASSWORD=${GMAIL_PASSWORD} -s AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET} ./webtask/src/findme.js
