image: node:7.4.0

stages:
  - build
  - test
  - deploy

build client:
  stage: build
  variables:
    NODE_ENV: "production"
  script:
    - npm install
    - npm run bundle
    
  artifacts:
    paths:
      - client/dist/
      - node_modules/
  
test:
  stage: test
  only:
    - master

  script:
    - npm test
    
  artifacts:
    paths:
      - client/dist/

pages:
  image: alpine:latest
  stage: deploy
  script:
  - mkdir public
  - cp client/dist/* public
  artifacts:
    paths:
    - public
  only:
  - master

webtask:
  stage: deploy
  only:
    - master

  script:
    - "echo '{\"default\": {\"url\": \"https://webtask.it.auth0.com\", \"token\": \"${TOKEN}\", \"container\": \"${CONTAINER}\"}}' > ~/.webtask"
    - npm install -g wt-cli
    - wt-cli create webtask/src/find-me.js 
