export const SET_CENTER = 'SET_CENTER'
export const SET_MARKER = 'SET_MARKER'
export const SET_ZOOM = 'SET_ZOOM'
export const SET_ADDRESS = 'SET_ADDRESS'
export const SET_SUBJECT = 'SET_SUBJECT'
export const SET_MESSAGE = 'SET_MESSAGE'
